apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root
  namespace: monitoring
spec:
  virtualhost:
    fqdn: local.projectcontour.io
  routes:
  - services:
    - name: prometheus-k8s
      port: 9090
